export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const MY_ALL_ORDER_REQUEST = "MY_ALL_ORDER_REQUEST";
export const MY_ALL_ORDER_SUCCESS = "MY_ALL_ORDER_SUCCESS";
export const MY_ALL_ORDER_FAIL = "MY_ALL_ORDER_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";